export enum Role {
  ADMIN = "ADMIN",
  HEAD_OF_EDUCATION = "HEAD_OF_EDUCATION",
  MANAGER_DIRECTOR = "MANAGER_DIRECTOR",
  MANAGEMENT = "MANAGEMENT",
  EVENT_DIRECTOR = "EVENT_DIRECTOR",
  TRAINER = "TRAINER",
  STUDENT = "STUDENT"
}
